feat(hardware-test): implement first automated hw test
es-ude/elastic-ai.runtime.enV5 pull request #324
Opened 2024-11-28 16:42 UTC by HerrCooker

2024-11-29 11:55 UTC, glencoe reviewed
I guess we had a small misunderstanding here (no wonder since i was in quite a hurry). What i want you to do is the following:

1. branch off from develop, e.g., you could call it `introduce-runtime-hw-tester`
2. add the python code there
3. open a pull request
4. after we merged that, rebase you cmake branch on develop so you have access to the script
5. continue your current bug hunt

2024-11-29 11:55 UTC, glencoe commented on .idea/elastic-ai.runtime.enV5.iml
please exclude this from the commit

2024-12-07 13:58 UTC, DavidFederl commented on python_utils/src/elasticai/testing/hw_test.py
> +    args = parser.parse_args()
Why don't you use the argparse library to check for the correct arguemnts and provide help?

```suggestion
    """running integration tests
    Help:
        execute `python3 ./hw_tst.py --help`
    """
    parser = argparse.ArgumentParser(prog="HW-Test", description="Hardware-Test Runner")
    parser.add_argument("-p", "--port", requierd=True, help="Device COM-Port")
    parser.add_argument("-t", "--test", requierd=True, help="Path to hardware-tests executables")
    parser.add_argument("-d", "--dir", requierd=True, help="??")
    args = parser.parse_args()
```

2025-02-03 09:39 UTC, glencoe requested changes
Only two requests remaining:

* [ ] please explain in the description of your commit message roughly how to use that new system for automated hardware tests and why it was added
* [x] please take care of the `pyproject.back.toml` file

2025-02-03 09:39 UTC, glencoe commented on pyproject.back.toml
Is this file used or not? If it's not used we should remove it, if it's used i'm wondering why it's called *.back.toml

2025-02-03 11:45 UTC, HerrCooker commented on test/hardware/Esp/CheckEspForOkViaPico.c
> +paramTest(cannotTalkToEspIfOnlySleepingForMsBeforeReceive, 1)
I'm not sure how to do that cleanly, as we use different assertions. Just add a macro for each different assertion? In this case it's just two, but in other cases the number of different assertions might be much higher.

2025-02-03 11:57 UTC, glencoe commented on test/hardware/Esp/CheckEspForOkViaPico.c
> +paramTest(cannotTalkToEspIfOnlySleepingForMsBeforeReceive, 1)
that makes sense, so for me that means it's not worth the effort ;)

2025-02-03 11:59 UTC, glencoe commented
good job: For future reference, i'd say the line `Why we added automated hardware tests:` is unnecessary as each commit body should tell us why the change was made in cases where it's not completely obvious, e.g., `fix typo` etc.

2025-02-03 11:59 UTC, glencoe approved these changes

2025-02-03 12:45 UTC, merged